version: "2"
services:
  prod:
    build:
      context: .
      args:
        PORTA_1: 5000
        PORTA_2: 5001
        BRANCH: "main"
    ports:
      - 5000:5000
      - 5001:5001
    restart: always
    container_name: HelpZap-Frontend