import Head from 'next/head'
import { Text, Box, Button } from '@chakra-ui/react'
import { useGlobalState, setGlobalState } from "@/globalStates"
import { useState, useEffect } from 'react'

export default function Home() {

  const [token, setToken] = useState("")

  useEffect(() => {
    // Perform localStorage action
    const item = localStorage.getItem('key')
    setToken(item)
  }, [])

  function handleClick() {
    token !== "0" ? window.location.href = "/mainApp" : window.location.href = "/login"
  }

  return (
    <>
      <Head>
        <title>Helpzap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box h='100vh' bg='#010715' display={'flex'} flexDir='column' justifyContent={'center'} alignItems='center'>
        <Box className='typewriter'>
          <Text cursor={'pointer'} onClick={handleClick} as='h1' className='animation ' fontSize={'60px'}>Helpzap 1.0b</Text>

        </Box>

        {/* <Text as={'a'} href={} color='blue.300' cursor={'pointer'} transition={"0.2s linear"} _hover={{ color: "cyan" }}>
          {token !== "0" ? "Acessar o chat" : "Fazer login"}
        </Text> */}

      </Box>
    </>
  )
}
